### ISSUE TITLE
Publish network weights

### ISSUE THREAD

**Issue by prhbrt** [joergfranke/phoneme_recognition#1]
Could you publish the network weights trained on TIMIT which worked best for you?

**Comment by JoergFranke** [comment]
Unfortunately, I haven't stored them. But you can easily train a network, should be done in a couple hours on a GPU.

**Comment by prhbrt** [comment]
I guess that's true, my results seem worse than the example in the Readme, was that one cherry-picked?

I get results like these:

![screenshot from 2017-03-13 14-19-52](https://cloud.githubusercontent.com/assets/7011110/23856226/43a5b1f8-07f9-11e7-8e33-c07ee7fd9f3f.png)

They make some sense, but are by far worse than your example:

![example](https://cloud.githubusercontent.com/assets/7011110/23856271/6619607c-07f9-11e7-8822-cf9c38082924.png)

**Comment by JoergFranke** [comment]
Do you know why your input feature prints lock different to mine? I'm not sure if I trained my model for the print only 20 epochs. Some models I experiment with are trained 50 epochs.

**Comment by prhbrt** [comment]
> Do you know why your input feature prints lock different to mine?

Different matplotlibs with different default colorschemes I think.

> I'm not sure if I trained my model for the print only 20 epochs. Some models I experiment with are trained 50 epochs.

Training output shows `epoch validation at 34/414`, did you train on 414 epochs? The model does still improve after 20 epochs.

**Comment by JoergFranke** [comment]
> Different matplotlibs with different default colorschemes I think.

I tried to repeat my experiments and i get the same green plots like you. It looks like they have less variance. 

> Training output shows epoch validation at 34/414, did you train on 414 epochs? The model does still improve after 20 epochs.

I trained with 20 or 50 epochs but not more. I picked this example because it was nice, but the other samples looked similar.
